# Ruby CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
#
version: 2
jobs:
  # The Build Job
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/ruby:2.4.1-node-browsers
    steps:
      # Checkout the code from the branch into the working_directory
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "Gemfile.lock" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      # Install project dependencies
      - run:
          name: "Install local dependencies"
          command: bundle install --jobs=4 --retry=3 --path vendor/bundle

      # Cache local dependencies if they don't exist
      - save_cache:
          paths:
            - ./vendor/bundle
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}

      # Install Widdershins
      - run:
          name: "Install Widdershins"
          command: npm install -g widdershins

      # Translate OpenAPI Spec YAML to Markdown
      - run:
          name: "Translate Open API Spec YAML to Markdown"
          command: node widdershins openapi.yaml -o source/index.html.md --language_tabs HTTP --summary true

      # Generate static content
      - run:
          name: "Build for Production"
          command: bundle exec middleman build --clean

      # Cache the build dolders for the deploy job
      - save_cache:
          key: v1-web-deploy-{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - build

  deploy:
    working_directory: ~/repo
    environment:
      - PRODUCTION_BRANCH: master
      - STAGING_BRANCH: staging
    docker:
      - image: circleci/node:7.10
    steps:
      - checkout
      - restore_cache:
          key: v1-web-deploy-{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: "Install pip and AWS CLI"
          command: |
            sudo apt-get -y -qq update
            sudo apt-get install python-pip python-dev build-essential
            sudo pip install awscli
      - run:
          name: Deploy to S3 Bucket
          command: |
            if [ "${CIRCLE_BRANCH}" == "${PRODUCTION_BRANCH}" ]; then
              aws s3 sync web_deploy s3://poc-api-docs-fdek0092jahdvsdmldlfwmisfnvi9j3fsiksn/hgnwkfsekgsx --delete
            elif [ "${CIRCLE_BRANCH}" == "${STAGING_BRANCH}" ]; then
              aws s3 sync web_deploy s3://poc-api-docs-fdek0092jahdvsdmldlfwmisfnvi9j3fsiksn/staging --delete
            fi

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
                - staging
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - master
                - staging
